name: test-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist-folder
        run: npm run build
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: upload dist-folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to github pages
        id: deployment
      - uses: action/deploy-pages@v1
